# Generated by Django 5.2.3 on 2026-01-10 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0002_remove_bounty_claims_left'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['status'], name='bounties_bo_status_aab492_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['created_at'], name='bounties_bo_created_c0e5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['expires_at'], name='bounties_bo_expires_a87726_idx'),
        ),
        migrations.AddIndex(
            model_name='bounty',
            index=models.Index(fields=['status', 'created_at'], name='bounties_bo_status_1fd076_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['status'], name='bounties_bo_status_5f1f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['created_at'], name='bounties_bo_created_c785c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['submitted_at'], name='bounties_bo_submitt_708adc_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['approved_at'], name='bounties_bo_approve_353c96_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['status', 'created_at'], name='bounties_bo_status_4619fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['bounty', 'status'], name='bounties_bo_bounty__4e1993_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyclaim',
            index=models.Index(fields=['user', 'status'], name='bounties_bo_user_id_ee71bb_idx'),
        ),
    ]
