# Generated by Django 5.2.3 on 2026-01-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0003_bounty_bounties_bo_status_aab492_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique redeem code', max_length=50, unique=True)),
                ('coins', models.IntegerField(help_text='Number of coins this code gives')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the code expires', null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='bounties_re_code_d6db26_idx'), models.Index(fields=['status'], name='bounties_re_status_a912b8_idx'), models.Index(fields=['expires_at'], name='bounties_re_expires_bd51b4_idx'), models.Index(fields=['status', 'expires_at'], name='bounties_re_status_aba735_idx')],
            },
        ),
    ]
