# Generated by Django 5.2.3 on 2026-01-10 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0004_redeemcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_balance', models.IntegerField(default=0, help_text="User's coin balance")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-user__date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Coin amount (positive for credits, negative for debits)')),
                ('transaction_type', models.CharField(choices=[('bounty_reward', 'Bounty Reward'), ('code_redemption', 'Code Redemption'), ('admin_adjustment', 'Admin Adjustment')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(help_text='ID of related object (bounty claim, redeem code, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bounties_co_user_id_bf535c_idx'), models.Index(fields=['transaction_type'], name='bounties_co_transac_bfeab9_idx'), models.Index(fields=['reference_id'], name='bounties_co_referen_c1be06_idx')],
            },
        ),
    ]
