# Generated by Django 5.2.11 on 2026-02-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0005_userprofile_cointransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Whether user has admin privileges'),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the auction item', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the auction item')),
                ('image_urls', models.JSONField(default=list, help_text='List of image URLs for the auction item')),
                ('starts_at', models.DateTimeField(help_text='When the auction becomes active and starts accepting bids')),
                ('ends_at', models.DateTimeField(help_text='When the auction ends and bidding closes')),
                ('minimum_bid', models.IntegerField(default=1, help_text='Minimum starting bid amount')),
                ('buyout_price', models.IntegerField(blank=True, help_text='Optional buyout price to end auction immediately', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_highest_bid', models.IntegerField(default=0, help_text='Current highest bid amount')),
                ('total_bids', models.IntegerField(default=0, help_text='Total number of bids placed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auctions', to=settings.AUTH_USER_MODEL)),
                ('current_highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Bid amount in coins')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('outbid', 'Outbid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_required', models.IntegerField(help_text='Minimum amount required for this bid')),
                ('previous_highest_bid', models.IntegerField(default=0, help_text='Previous highest bid when this bid was placed')),
                ('coins_reserved', models.BooleanField(default=False, help_text='Whether coins have been reserved for this bid')),
                ('coins_deducted', models.BooleanField(default=False, help_text='Whether coins have been deducted from user balance')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bounties.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_amount', models.IntegerField(help_text='Final winning bid amount')),
                ('coins_transferred', models.BooleanField(default=False, help_text='Whether coins have been transferred to admin/system')),
                ('transfer_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='bounties.auction')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status'], name='bounties_au_status_e402fb_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['starts_at'], name='bounties_au_starts__24a18c_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['ends_at'], name='bounties_au_ends_at_47c0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'starts_at'], name='bounties_au_status_fd4661_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'ends_at'], name='bounties_au_status_904d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['current_highest_bid'], name='bounties_au_current_57ddeb_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['created_at'], name='bounties_au_created_53674b_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['auction', 'status'], name='bounties_au_auction_29e7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['user', 'status'], name='bounties_au_user_id_cc2e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['amount'], name='bounties_au_amount_a84816_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['created_at'], name='bounties_au_created_c53236_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['auction', 'amount'], name='bounties_au_auction_670a70_idx'),
        ),
        migrations.AddConstraint(
            model_name='auctionbid',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('auction', 'user'), name='unique_active_bid_per_user'),
        ),
        migrations.AddIndex(
            model_name='auctionwinner',
            index=models.Index(fields=['winner'], name='bounties_au_winner__d0113a_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionwinner',
            index=models.Index(fields=['created_at'], name='bounties_au_created_9e3399_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionwinner',
            index=models.Index(fields=['coins_transferred'], name='bounties_au_coins_t_f086bd_idx'),
        ),
    ]
