# Generated by Django 5.2.11 on 2026-02-14 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0006_userprofile_is_admin_auction_auctionbid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bounties_auction_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auction',
            name='bounties_au_status_fd4661_idx',
        ),
        migrations.RemoveIndex(
            model_name='auction',
            name='bounties_au_status_904d6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='auction',
            name='bounties_au_current_57ddeb_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='bounties_au_status_490418_idx',
            old_name='bounties_au_status_e402fb_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='bounties_au_starts__383c68_idx',
            old_name='bounties_au_starts__24a18c_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='bounties_au_ends_at_08e2a2_idx',
            old_name='bounties_au_ends_at_47c0ef_idx',
        ),
        migrations.RenameIndex(
            model_name='auction',
            new_name='bounties_au_created_74b145_idx',
            old_name='bounties_au_created_53674b_idx',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='buyout_price',
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_bid_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ends_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimum_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starts_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auction',
            name='total_bids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='auction',
            table='bounties_auctions',
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bounties.auction'),
        ),
    ]
