# Generated by Django 5.2.11 on 2026-02-17 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0007_auctionimage_alter_auction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('bounty_reward', 'Bounty Reward'), ('code_redemption', 'Code Redemption'), ('admin_adjustment', 'Admin Adjustment'), ('playengine_transfer', 'PlayEngine Transfer')], max_length=20),
        ),
        migrations.CreateModel(
            name='PointTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='User email used for PlayEngine transfer', max_length=254)),
                ('amount', models.PositiveIntegerField(help_text='Transfer amount requested')),
                ('transfer_id', models.UUIDField(help_text='Server-generated UUID sent to PlayEngine', unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('playengine_error', models.CharField(blank=True, max_length=100)),
                ('playengine_response', models.JSONField(blank=True, default=dict)),
                ('credited_balance', models.IntegerField(blank=True, help_text='Local balance after credit on success', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bounties_po_user_id_7502de_idx'), models.Index(fields=['transfer_id'], name='bounties_po_transfe_e6be95_idx'), models.Index(fields=['status'], name='bounties_po_status_47e20e_idx')],
            },
        ),
    ]
